name: auto-merge-common-config.yml
on:
  push:
    branches: [ common ]

jobs:
  merge-common-config:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run script
        run: bash .github/merge-common-and-push.sh 2>&1 > bash-log.log
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload log
        use: actions/upload-artifact@v4
        with:
          path: bash-log.log
